#!/usr/bin/env python3
"""Generate CASES.md from the committed case files.

Generated, never hand-written: an index maintained by hand drifts from the cases it
indexes, and the whole point of committing the case is that the file is the record.

    python scripts/make_cases_index.py
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CASES = ROOT / "assets" / "cases"


STRONG_EVIDENCE = {1, 2, 3}     # approved-drug label / mechanism / human LoF genetics


def violations(card: dict) -> list[str]:
    """G10: an anti-target needs evidence of class 1-3 to be registered.

    Class 4 is structural similarity, which says "it could bind", not "binding it is
    bad". Registering on similarity alone is how STATE.md section 7's gaps 7b and 7c
    happened — the off-targets were chosen because they were in the family and
    nobody was asked for safety evidence.

    Enforced here rather than in a test alone: this is the one place that already
    reads every card, so a card that violates the rule cannot produce an index.
    """
    found = []
    for name, evidence in card.get("anti_target_evidence", {}).items():
        classes = set(evidence.get("class", []))
        if evidence.get("registered") and not (classes & STRONG_EVIDENCE):
            found.append(f"{card['case_id']}: {name} is registered on class "
                         f"{sorted(classes)} only — G10 requires one of 1, 2 or 3")
    listed = set(card.get("anti_target_evidence", {}))
    missing = [o for o in card.get("offs", []) if o not in listed]
    if missing:
        found.append(f"{card['case_id']}: off-targets with no evidence entry at all: "
                     f"{missing}")
    return found


def _rounds(directory: Path) -> list[dict]:
    path = directory / "rounds.jsonl"
    if not path.exists():
        return []
    return [json.loads(line) for line in path.read_text().splitlines() if line.strip()]


def main() -> None:
    lines = ["# Cases", "",
             "Generated by `python scripts/make_cases_index.py`. Do not edit by hand.",
             "",
             "Enrichment is reported against its ceiling, never alone: the pool empties",
             "of selective molecules as the loop consumes them, so the base rate falls",
             "and the same ranking scores a higher raw enrichment each round.",
             "",
             "| Case | Panel | Indication | Rounds | Last acquired hit | vs random | Enrichment (% of ceiling) |",
             "|---|---|---|---:|---:|---:|---:|"]
    for directory in sorted(p for p in CASES.iterdir() if p.is_dir()):
        card_file = directory / "panel.json"
        if not card_file.exists():
            continue
        card = json.loads(card_file.read_text())
        broken = violations(card)
        if broken:
            raise SystemExit("G10 violation, refusing to write the index:\n  "
                             + "\n  ".join(broken))
        rounds = _rounds(directory)
        if rounds:
            last = rounds[-1]["metrics"]
            hit = f"{last['acquired']['hit_rate']:.1%}"
            adv = f"{last['advantage']:+.1%}"
            share = (f"{last['enrichment']:.2f}x "
                     f"({last['enrichment'] / last['enrichment_ceiling']:.0%})")
        else:
            hit = adv = share = "—"
        lines.append(f"| [{card['case_id']}](assets/cases/{directory.name}/program.md) "
                     f"| {card['panel']} | {card['indication']} | {len(rounds)} "
                     f"| {hit} | {adv} | {share} |")
    (ROOT / "CASES.md").write_text("\n".join(lines) + "\n")
    print(f"Wrote {ROOT / 'CASES.md'}")


if __name__ == "__main__":
    main()
